print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/kieranbasu/Desktop/week01/week01/Assets/Models/Rube_Goldberg_Track_Model.ma"`)
{		
	file -o "/Users/kieranbasu/Desktop/week01/week01/Assets/Models/Rube_Goldberg_Track_Model.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/kieranbasu/Desktop/week01/week01/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/kieranbasu/Desktop/week01/week01/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/kieranbasu/Desktop/week01/week01/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
